#include "autonomy_config.h"
#include "command_smoother.h"
#include "frontier_detector.h"
#include "frontier_history.h"
#include "frontier_scorer.h"
#include "local_path_planner.h"
#include "mission_state_machine.h"
#include "occupancy_grid.h"
#include "progress_monitor.h"
#include "safety_gates.h"
#include <math.h>
#include <stdio.h>
#include <string.h>

static int failures=0,tests=0;
#define CHECK(x) do{tests++;if(!(x)){fprintf(stderr,"FAIL %s:%d: %s\n",__FILE__,__LINE__,#x);failures++;}}while(0)
static OccupancyGrid grid_make(CellState*c,int w,int h,float res,uint64_t stamp,CellState fill){OccupancyGrid g={c,(uint16_t)w,(uint16_t)h,res,-w*res*.5f,-h*res*.5f,stamp,1,FRAME_LOCAL_NED,true,false};for(int i=0;i<w*h;++i)c[i]=fill;return g;}
static GridPoint point_at(const OccupancyGrid*g,int x,int y){GridPoint p;occupancy_grid_cell_to_world(g,x,y,&p.x_m,&p.y_m);return p;}

static void test_grid(void){CellState a[100],b[100];OccupancyGrid g=grid_make(a,10,10,.1f,1000,CELL_UNKNOWN);int x,y;float wx,wy;
 CHECK(occupancy_grid_validate(&g,1100,200)==GRID_OK);CHECK(occupancy_grid_validate(&g,1300,200)==GRID_STALE);CHECK(occupancy_grid_world_to_cell(&g,0,0,&x,&y));CHECK(x==5&&y==5);CHECK(occupancy_grid_cell_to_world(&g,x,y,&wx,&wy));CHECK(occupancy_grid_get(&g,0,0)==CELL_UNKNOWN);CHECK(!occupancy_grid_is_plannable(CELL_UNKNOWN));CHECK(!occupancy_grid_world_to_cell(&g,99,99,&x,&y));
 g.resolution_m=0;CHECK(occupancy_grid_validate(&g,1000,100)==GRID_INVALID_RESOLUTION);g.resolution_m=.1f;occupancy_grid_set(&g,5,5,CELL_OCCUPIED);OccupancyGrid d=g;d.cells=b;CHECK(occupancy_grid_inflate(&g,&d,.2f));CHECK(occupancy_grid_get(&d,5,5)==CELL_OCCUPIED);CHECK(occupancy_grid_get(&d,6,5)==CELL_INFLATED_OBSTACLE);CHECK(occupancy_grid_get(&d,0,0)==CELL_UNKNOWN);CHECK(occupancy_grid_clearance_m(&d,0,0,1.0f)<=.101f);
}

static void test_frontier(void){static CellState cells[400];OccupancyGrid g=grid_make(cells,20,20,.1f,1000,CELL_UNKNOWN);for(int y=5;y<=12;++y)for(int x=5;x<=12;++x)occupancy_grid_set(&g,x,y,CELL_FREE);AutonomyConfig c=autonomy_config_defaults();c.vehicle_radius_m=c.propeller_guard_margin_m=c.pose_uncertainty_margin_m=c.mapping_uncertainty_margin_m=c.additional_safety_margin_m=.01f;c.minimum_frontier_cells=3;FrontierWorkspace w;FrontierSet s;CHECK(frontier_detect(&g,&c,1000,&w,&s));CHECK(s.accepted_count==1);CHECK(s.accepted[0].cell_count>3);int gx,gy;CHECK(occupancy_grid_world_to_cell(&g,s.accepted[0].goal.x_m,s.accepted[0].goal.y_m,&gx,&gy));CHECK(occupancy_grid_get(&g,gx,gy)==CELL_FREE);
 for(int i=0;i<400;++i) cells[i]=CELL_OCCUPIED;
 CHECK(frontier_detect(&g,&c,1000,&w,&s));CHECK(s.accepted_count==0);
 for(int i=0;i<400;++i) cells[i]=CELL_UNKNOWN;
 occupancy_grid_set(&g,10,10,CELL_FREE);CHECK(frontier_detect(&g,&c,1000,&w,&s));CHECK(s.accepted_count==0&&s.rejected_count==1&&s.rejected[0].reason==FRONTIER_REJECT_TOO_SMALL);
 for(int i=0;i<400;++i) cells[i]=CELL_UNKNOWN;
 c.minimum_frontier_cells=2;
 occupancy_grid_set(&g,3,3,CELL_FREE);occupancy_grid_set(&g,4,3,CELL_FREE);occupancy_grid_set(&g,14,14,CELL_FREE);occupancy_grid_set(&g,15,14,CELL_FREE);CHECK(frontier_detect(&g,&c,1000,&w,&s));CHECK(s.accepted_count==2);
 GridPoint first_goal=s.accepted[0].goal;CHECK(frontier_detect(&g,&c,1000,&w,&s));CHECK(s.accepted[0].goal.x_m==first_goal.x_m&&s.accepted[0].goal.y_m==first_goal.y_m);
 for(int i=0;i<400;++i) cells[i]=CELL_OCCUPIED;
 for(int y=8;y<=10;++y)for(int x=8;x<=10;++x)if(x==8||x==10||y==8||y==10)occupancy_grid_set(&g,x,y,CELL_FREE);
 occupancy_grid_set(&g,9,9,CELL_UNKNOWN);c.minimum_frontier_cells=3;CHECK(frontier_detect(&g,&c,1000,&w,&s));CHECK(s.accepted_count==1);int cx,cy;CHECK(occupancy_grid_world_to_cell(&g,s.accepted[0].centroid.x_m,s.accepted[0].centroid.y_m,&cx,&cy));CHECK(occupancy_grid_get(&g,cx,cy)==CELL_UNKNOWN);CHECK(occupancy_grid_world_to_cell(&g,s.accepted[0].goal.x_m,s.accepted[0].goal.y_m,&gx,&gy)&&occupancy_grid_get(&g,gx,gy)==CELL_FREE);
}

static void test_scoring(void){AutonomyConfig c=autonomy_config_defaults();FrontierCandidate f[3];memset(f,0,sizeof(f));for(int i=0;i<3;++i){f[i].id=i+1;f[i].reachable=true;f[i].expected_unknown_gain=10;f[i].path_distance_m=1;f[i].clearance_m=1;}
 f[0].obstacle_risk=5;f[1].path_distance_m=2;CHECK(frontier_select_best(f,2,&c)==1);f[1].revisit_penalty=10;CHECK(frontier_select_best(f,2,&c)==0);f[0].reachable=false;CHECK(frontier_select_best(f,1,&c)==-1);f[0].reachable=true;f[0].expected_unknown_gain=5;f[1].revisit_penalty=0;f[1].expected_unknown_gain=20;CHECK(frontier_select_best(f,2,&c)==1);f[1].uncertainty=20;CHECK(frontier_select_best(f,2,&c)==0);
}

static void test_history_progress(void){FrontierHistory h={0};GridPoint g={1,2};CHECK(frontier_history_penalty(&h,g,1000,.2f)==0.0f);frontier_history_record(&h,g,1000,true,.2f);CHECK(frontier_history_penalty(&h,g,1000,.2f)>3.0f);frontier_history_record(&h,g,2000,false,.2f);CHECK(h.entries[0].attempts==2&&h.entries[0].failures==1);
 AutonomyConfig c=autonomy_config_defaults();c.progress_timeout_s=1.0f;ProgressMonitor m;VehiclePose p={.x_m=0,.y_m=0,.vx_mps=0,.vy_mps=0,.valid=true};progress_monitor_start(&m,(GridPoint){0,0},(GridPoint){1,0},0);CHECK(progress_monitor_update(&m,&p,500,&c)==PROGRESS_OK);CHECK(progress_monitor_update(&m,&p,1100,&c)==PROGRESS_STALLED);p.x_m=.95f;CHECK(progress_monitor_update(&m,&p,1200,&c)==PROGRESS_REACHED);progress_monitor_start(&m,(GridPoint){0,0},(GridPoint){1,0},0);p.x_m=-.3f;CHECK(progress_monitor_update(&m,&p,100,&c)==PROGRESS_DIVERGED);progress_monitor_start(&m,(GridPoint){0,0},(GridPoint){1,0},0);p.x_m=0;p.vx_mps=1;CHECK(progress_monitor_update(&m,&p,100,&c)==PROGRESS_EXCESS_SPEED);
}

static void test_planner(void){static CellState cells[900],inflated_cells[900];OccupancyGrid g=grid_make(cells,30,30,.1f,1000,CELL_FREE);AutonomyConfig c=autonomy_config_defaults();c.planner_search_radius_m=10;c.planner_max_path_m=20;c.planner_max_nodes=900;PlannerWorkspace w;LocalPath p;GridPoint a=point_at(&g,2,2),b=point_at(&g,25,2);CHECK(local_path_plan(&g,a,b,&c,&w,&p)==PLAN_OK);CHECK(p.valid&&p.count==24);GridPoint extracted;CHECK(local_path_next_subgoal(&p,a,.35f,&extracted));CHECK(hypotf(extracted.x_m-a.x_m,extracted.y_m-a.y_m)<=.351f);CHECK(local_path_plan(&g,point_at(&g,0,0),point_at(&g,0,5),&c,&w,&p)==PLAN_OK);occupancy_grid_set(&g,10,2,CELL_OCCUPIED);CHECK(local_path_plan(&g,a,b,&c,&w,&p)==PLAN_OK&&p.turn_count>=2);occupancy_grid_set(&g,25,2,CELL_OCCUPIED);CHECK(local_path_plan(&g,a,b,&c,&w,&p)==PLAN_GOAL_BLOCKED);occupancy_grid_set(&g,25,2,CELL_FREE);
 for(int y=0;y<30;++y) occupancy_grid_set(&g,15,y,CELL_OCCUPIED);
 occupancy_grid_set(&g,15,15,CELL_FREE);OccupancyGrid ig=g;ig.cells=inflated_cells;CHECK(occupancy_grid_inflate(&g,&ig,autonomy_required_clearance_m(&c,g.resolution_m)));a=point_at(&g,5,15);b=point_at(&g,25,15);CHECK(local_path_plan(&ig,a,b,&c,&w,&p)==PLAN_NO_PATH);
 for(int y=0;y<30;++y) for(int x=0;x<30;++x) occupancy_grid_set(&g,x,y,CELL_UNKNOWN);
 occupancy_grid_set(&g,2,2,CELL_FREE);occupancy_grid_set(&g,3,2,CELL_FREE);CHECK(local_path_plan(&g,point_at(&g,2,2),point_at(&g,3,2),&c,&w,&p)==PLAN_OK);CHECK(local_path_plan(&g,point_at(&g,2,2),point_at(&g,4,2),&c,&w,&p)==PLAN_GOAL_BLOCKED);c.planner_max_nodes=1;CHECK(local_path_plan(&g,point_at(&g,2,2),point_at(&g,3,2),&c,&w,&p)==PLAN_SEARCH_LIMIT);c.planner_max_nodes=900;c.maximum_frontier_step_m=.05f;GridPoint sub;CHECK(local_path_next_subgoal(&p,a,.2f,&sub)==false);
}

static MissionContext valid_context(OccupancyGrid*g,uint64_t now){MissionContext x={0};x.now_ms=now;x.heartbeat_timestamp_ms=x.tof_timestamp_ms=x.range_timestamp_ms=x.optical_flow_timestamp_ms=now;x.pose=(VehiclePose){0,0,.5f,0,0,0,0,.05f,now,true};x.map=g;x.range_altitude_m=.5f;x.battery_v=8;x.nearest_obstacle_m=1;x.optical_flow_quality=100;x.heartbeat_valid=x.expected_mode=x.vehicle_state_valid=x.battery_valid=x.path_valid=x.subgoal_valid=x.command_valid=x.horizontal_motion_requested=x.mission_state_valid=true;return x;}
static void test_safety(void){CellState cells[100];OccupancyGrid g=grid_make(cells,10,10,.1f,1000,CELL_FREE);AutonomyConfig c=autonomy_config_defaults();SafetyMonitor m={0};MissionContext x=valid_context(&g,1000);CHECK(evaluate_safety(&x,&c,&m).decision==SAFETY_OK);x.pose.timestamp_ms=1;CHECK(evaluate_safety(&x,&c,&m).decision==SAFETY_HOVER);x.now_ms=4000;g.timestamp_ms=4000;x.heartbeat_timestamp_ms=x.tof_timestamp_ms=x.range_timestamp_ms=x.optical_flow_timestamp_ms=4000;CHECK(evaluate_safety(&x,&c,&m).decision==SAFETY_LAND);m=(SafetyMonitor){0};x=valid_context(&g,4000);g.timestamp_ms=1;CHECK(evaluate_safety(&x,&c,&m).reason==SAFETY_REASON_MAP);g.timestamp_ms=4000;x.tof_timestamp_ms=1;CHECK(evaluate_safety(&x,&c,&m).reason==SAFETY_REASON_TOF);x=valid_context(&g,4000);x.range_timestamp_ms=1;CHECK(evaluate_safety(&x,&c,&m).reason==SAFETY_REASON_RANGE);x=valid_context(&g,4000);x.optical_flow_quality=1;CHECK(evaluate_safety(&x,&c,&m).reason==SAFETY_REASON_OPTICAL_FLOW);x=valid_context(&g,4000);x.heartbeat_valid=false;CHECK(evaluate_safety(&x,&c,&m).decision==SAFETY_LAND);x=valid_context(&g,4000);x.distance_from_mission_origin_m=c.maximum_mission_radius_m+.1f;CHECK(evaluate_safety(&x,&c,&m).reason==SAFETY_REASON_MISSION_RADIUS);x=valid_context(&g,4000);x.battery_v=5;CHECK(evaluate_safety(&x,&c,&m).reason==SAFETY_REASON_BATTERY);x=valid_context(&g,4000);x.manual_stop=true;CHECK(evaluate_safety(&x,&c,&m).reason==SAFETY_REASON_MANUAL_STOP);x=valid_context(&g,4000);x.nearest_obstacle_m=.01f;CHECK(evaluate_safety(&x,&c,&m).reason==SAFETY_REASON_OBSTACLE);x=valid_context(&g,4000);x.expected_mode=false;CHECK(evaluate_safety(&x,&c,&m).reason==SAFETY_REASON_MODE);x=valid_context(&g,4000);x.pose.x_m=NAN;CHECK(evaluate_safety(&x,&c,&m).reason==SAFETY_REASON_POSE);x=valid_context(&g,4000);x.command_valid=false;CHECK(evaluate_safety(&x,&c,&m).reason==SAFETY_REASON_COMMAND);
}

static void test_smoother(void){AutonomyConfig c=autonomy_config_defaults();CommandSmoother s={0};MotionCommand r={10,-10,10,100,1000,true},o;bool clamped;CHECK(command_smoother_update(&s,&c,&r,1000,true,false,&o,&clamped));CHECK(clamped&&hypotf(o.vx_mps,o.vy_mps)<=c.max_horizontal_speed_mps&&fabsf(o.vz_mps)<=c.max_vertical_speed_mps&&fabsf(o.yaw_rate_dps)<=c.max_yaw_rate_dps);MotionCommand previous=o;r=(MotionCommand){-10,10,0,-100,1050,true};CHECK(command_smoother_update(&s,&c,&r,1050,true,false,&o,&clamped));CHECK(hypotf(o.vx_mps-previous.vx_mps,o.vy_mps-previous.vy_mps)<=c.max_acceleration_mps2*.05f+.0001f);r.vx_mps=NAN;CHECK(!command_smoother_update(&s,&c,&r,1100,true,false,&o,&clamped));r=(MotionCommand){1,1,0,0,1000,true};CHECK(command_smoother_update(&s,&c,&r,2000,false,false,&o,&clamped));CHECK(o.vx_mps==0.0f&&o.vy_mps==0.0f);r=(MotionCommand){1,0,0,0,1,true};CHECK(command_smoother_update(&s,&c,&r,3000,true,false,&o,&clamped));CHECK(clamped&&fabsf(o.vx_mps)<=c.max_acceleration_mps2*(2.0f/c.command_rate_hz)+.0001f);GridPoint limited;CHECK(command_limit_subgoal((GridPoint){0,0},(GridPoint){10,0},.25f,&limited));CHECK(fabsf(limited.x_m-.25f)<1e-5f);
}

static MissionOutput mtick(MissionStateMachine*m,uint64_t t,MissionInput*i,AutonomyConfig*c){i->now_ms=t;return mission_state_machine_tick(m,i,c);}
static void test_mission(void){AutonomyConfig c=autonomy_config_defaults();MissionStateMachine m;MissionInput i={0};mission_state_machine_init(&m,0);mtick(&m,0,&i,&c);CHECK(m.state==MISSION_PREFLIGHT_CHECK);i.preflight_valid=i.start_requested=true;mtick(&m,10,&i,&c);CHECK(m.state==MISSION_WAIT_HEARTBEAT);i.heartbeat_fresh=true;mtick(&m,20,&i,&c);CHECK(m.state==MISSION_SET_MODE);i.mode_ack=i.mode_observed=true;mtick(&m,30,&i,&c);CHECK(m.state==MISSION_ARM_REQUESTED);i.arm_ack=i.armed_observed=true;mtick(&m,40,&i,&c);CHECK(m.state==MISSION_TAKEOFF);i.takeoff_ack=i.altitude_increased=i.altitude_at_target=true;mtick(&m,50,&i,&c);CHECK(m.state==MISSION_HOVER_STABILIZE);CHECK(m.state!=MISSION_EXPLORE);i.hover_stable=true;mtick(&m,100,&i,&c);mtick(&m,1700,&i,&c);CHECK(m.state==MISSION_HOVER_SCAN);i.scan_fresh=true;i.exploration_enabled=true;mtick(&m,2800,&i,&c);CHECK(m.state==MISSION_SELECT_FRONTIER);i.frontier_available=true;mtick(&m,2810,&i,&c);CHECK(m.state==MISSION_PLAN_PATH);i.path_available=true;mtick(&m,2820,&i,&c);CHECK(m.state==MISSION_EXPLORE);i.safety_decision=SAFETY_HOVER;mtick(&m,2830,&i,&c);CHECK(m.state==MISSION_HOLD);i.safety_decision=SAFETY_OK;i.interrupt_requested=true;MissionOutput o=mtick(&m,2840,&i,&c);CHECK(m.state==MISSION_LAND&&o.action==ACTION_LAND);i.interrupt_requested=false;i.landed_observed=true;mtick(&m,2850,&i,&c);CHECK(m.state==MISSION_DISARM);i.disarmed_observed=true;mtick(&m,2860,&i,&c);CHECK(m.state==MISSION_COMPLETE);
 mission_state_machine_init(&m,0);m.state=MISSION_WAIT_HEARTBEAT;m.entered_ms=0;i=(MissionInput){0};mtick(&m,6000,&i,&c);CHECK(m.state==MISSION_FAILSAFE);mission_state_machine_init(&m,0);m.state=MISSION_TAKEOFF;m.entered_ms=0;i=(MissionInput){.takeoff_ack=true,.altitude_increased=true};mtick(&m,11000,&i,&c);CHECK(m.state==MISSION_LAND);
 mission_state_machine_init(&m,0);m.state=MISSION_HOVER_SCAN;m.entered_ms=0;i=(MissionInput){0};mtick(&m,(uint64_t)(c.transient_hold_timeout_s*1000.0f)+1,&i,&c);CHECK(m.state==MISSION_HOLD);
 mission_state_machine_init(&m,0);m.state=MISSION_SET_MODE;i=(MissionInput){0};mtick(&m,5000,&i,&c);CHECK(m.state==MISSION_FAILSAFE);mission_state_machine_init(&m,0);m.state=MISSION_ARM_REQUESTED;i=(MissionInput){0};mtick(&m,6000,&i,&c);CHECK(m.state==MISSION_FAILSAFE);mission_state_machine_init(&m,0);m.state=MISSION_TAKEOFF;i=(MissionInput){0};mtick(&m,4000,&i,&c);CHECK(m.state==MISSION_LAND);mission_state_machine_init(&m,0);m.state=MISSION_PLAN_PATH;m.recovery_failures=c.maximum_recovery_failures-1;i=(MissionInput){0};mtick(&m,2000,&i,&c);CHECK(m.state==MISSION_LAND);mission_state_machine_init(&m,0);m.state=MISSION_SELECT_FRONTIER;i=(MissionInput){0};mtick(&m,3000,&i,&c);CHECK(m.state==MISSION_RETURN_OR_LAND);mission_state_machine_init(&m,0);m.state=MISSION_DISARM;i=(MissionInput){.landed_observed=false,.armed_observed=true};MissionOutput disarm=mtick(&m,100,&i,&c);CHECK(m.state==MISSION_LAND&&disarm.action==ACTION_LAND);
 mission_state_machine_init(&m,0);m.state=MISSION_LAND;i=(MissionInput){.armed_observed=true};mtick(&m,20001,&i,&c);CHECK(m.state==MISSION_FAILSAFE);mission_state_machine_init(&m,0);m.state=MISSION_DISARM;i=(MissionInput){.landed_observed=true,.armed_observed=true};mtick(&m,5001,&i,&c);CHECK(m.state==MISSION_LAND);
}
int main(void){test_grid();test_frontier();test_scoring();test_history_progress();test_planner();test_safety();test_smoother();test_mission();printf("autonomy tests: %d checks, %d failures\n",tests,failures);return failures?1:0;}
