#include "run_logger.h"
#include "safety_gates.h"
#include <string.h>

bool run_logger_open(RunLogger*l,const char*dir,uint64_t start){if(!l||!dir)return false;memset(l,0,sizeof(*l));snprintf(l->directory,sizeof(l->directory),"%s",dir);char path[768];snprintf(path,sizeof(path),"%s/decisions.csv",dir);l->events=fopen(path,"w");if(!l->events)return false;snprintf(path,sizeof(path),"%s/frontiers.csv",dir);l->frontiers=fopen(path,"w");snprintf(path,sizeof(path),"%s/telemetry.csv",dir);l->telemetry=fopen(path,"w");if(!l->frontiers||!l->telemetry){if(l->frontiers)fclose(l->frontiers);if(l->telemetry)fclose(l->telemetry);fclose(l->events);l->events=l->frontiers=l->telemetry=NULL;return false;}l->start_ms=start;fprintf(l->events,"timestamp_ms,event,reason,state,safety,safety_reason,vx_mps,vy_mps,vz_mps,yaw_rate_dps\n");fprintf(l->frontiers,"timestamp_ms,cluster_id,status,cell_count,gain,path_distance_m,heading_change_deg,obstacle_risk,revisit_penalty,uncertainty,path_complexity,clearance_m,total_score\n");fprintf(l->telemetry,"timestamp_ms,state,mode,armed,heartbeat_age_ms,pose_age_ms,map_age_ms,tof_age_ms,range_age_ms,flow_age_ms,flow_quality,battery_v,altitude_m,nearest_obstacle_m,path_length_m,path_clearance_m,subgoal_x_m,subgoal_y_m\n");return true;}
void run_logger_event(RunLogger*l,uint64_t t,const char*e,const char*r,MissionState s,SafetyResult safety,const MotionCommand*c){if(!l||!l->events)return;fprintf(l->events,"%llu,%s,%s,%s,%d,%s,%.4f,%.4f,%.4f,%.4f\n",(unsigned long long)t,e?e:"",r?r:"",mission_state_name(s),(int)safety.decision,safety_reason_name(safety.reason),c?c->vx_mps:0.0f,c?c->vy_mps:0.0f,c?c->vz_mps:0.0f,c?c->yaw_rate_dps:0.0f);}
void run_logger_frontier(RunLogger*l,uint64_t t,const FrontierCandidate*f){if(!l||!l->frontiers||!f)return;fprintf(l->frontiers,"%llu,%u,accepted,%u,%.4f,%.4f,%.4f,%.4f,%.4f,%.4f,%.4f,%.4f,%.4f\n",(unsigned long long)t,f->id,f->cell_count,f->expected_unknown_gain,f->path_distance_m,f->heading_change_deg,f->obstacle_risk,f->revisit_penalty,f->uncertainty,f->path_complexity,f->clearance_m,f->score);}
void run_logger_frontier_rejection(RunLogger*l,uint64_t t,uint32_t id,const char*reason){if(!l||!l->frontiers)return;fprintf(l->frontiers,"%llu,%u,%s,0,0,0,0,0,0,0,0,0,0\n",(unsigned long long)t,id,reason?reason:"rejected");}
static unsigned long long age(uint64_t now,uint64_t stamp){return stamp&&now>=stamp?(unsigned long long)(now-stamp):UINT64_MAX;}
void run_logger_telemetry(RunLogger*l,const MissionContext*x,MissionState s,bool armed,uint32_t mode,const LocalPath*p,const GridPoint*g){if(!l||!l->telemetry||!x)return;fprintf(l->telemetry,"%llu,%s,%u,%d,%llu,%llu,%llu,%llu,%llu,%llu,%u,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f\n",(unsigned long long)x->now_ms,mission_state_name(s),mode,armed?1:0,age(x->now_ms,x->heartbeat_timestamp_ms),age(x->now_ms,x->pose.timestamp_ms),x->map?age(x->now_ms,x->map->timestamp_ms):UINT64_MAX,age(x->now_ms,x->tof_timestamp_ms),age(x->now_ms,x->range_timestamp_ms),age(x->now_ms,x->optical_flow_timestamp_ms),(unsigned)x->optical_flow_quality,x->battery_v,x->pose.z_m,x->nearest_obstacle_m,p&&p->valid?p->distance_m:0.0f,p&&p->valid?p->minimum_clearance_m:0.0f,g?g->x_m:0.0f,g?g->y_m:0.0f);}
void run_logger_close(RunLogger*l){if(l&&l->events){fflush(l->events);fclose(l->events);l->events=NULL;}if(l&&l->frontiers){fflush(l->frontiers);fclose(l->frontiers);l->frontiers=NULL;}if(l&&l->telemetry){fflush(l->telemetry);fclose(l->telemetry);l->telemetry=NULL;}}
